services:
  migrate:
    build:
      context: .
      dockerfile: './Dockerfile'
    volumes:
      - "./data:/data"
    command: bun run migrate.ts

  bot:
    build:
      context: .
      dockerfile: './Dockerfile'
    restart: unless-stopped
    volumes:
      - "./data:/data"
    depends_on:
      migrate:
        condition: service_completed_successfully