import { Events as FluxerEvents, Client as FluxerClient } from "@fluxerjs/core";
import { Client as DiscordClient, Events as DiscordEvents, GatewayIntentBits } from "discord.js";
import Config from "./config";
import { DiscordCreateMessageHandler, FluxerCreateMessageHandler, FluxerDeleteMessageHandler, FluxerUpdateMessageHandler } from "./utils/MessageHandler";
import { log } from "./utils/Logger";
import fs from "node:fs";

const discordClient: DiscordClient<boolean> = new DiscordClient({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent
  ]
});

const fluxerClient = new FluxerClient({ intents: 0 });

discordClient.on(DiscordEvents.MessageCreate, (msg) => {
  if (msg.author.id === discordClient.user?.id) return;
  DiscordCreateMessageHandler(msg, discordClient, fluxerClient)
});

fluxerClient.on(FluxerEvents.MessageCreate, (msg) => {
  if (msg.author.id === fluxerClient.user?.id) return;
  FluxerCreateMessageHandler(msg, fluxerClient, discordClient)
});
fluxerClient.on(FluxerEvents.MessageUpdate, (oldMsg, newMsg) => {
  if (newMsg.author.id === fluxerClient.user?.id) return;
  FluxerUpdateMessageHandler(oldMsg, newMsg, fluxerClient)
});
fluxerClient.on(FluxerEvents.MessageDelete, (msg) => {
  if (msg.author.id === fluxerClient.user?.id) return;
  FluxerDeleteMessageHandler(msg, fluxerClient)
});

fluxerClient.on(FluxerEvents.Ready, async () => {
  log('FLUXER', `${fluxerClient.user?.username}#${fluxerClient.user?.discriminator} is ready!`)

  if (!fs.existsSync(Config.DataFolderPath + '/fluxcord.json')) {
    log('META', 'Welcome to Fluxcord! Doing first-time setup...')
    const replyL = fs.readFileSync(Config.DataFolderPath + '/reply-l.webp')
    const replyR = fs.readFileSync(Config.DataFolderPath + '/reply-r.webp')

    const fluxerGuild = await fluxerClient.guilds.fetch(Config.FluxerTempEmojiGuildId)
    await fluxerGuild?.createEmojisBulk([{
      image: replyL.toBase64(),
      name: 'reply_l'
    }, {
      image: replyR.toBase64(),
      name: 'reply_r'
    }])

    const fluxerEmojiReplyL = await fluxerClient.resolveEmoji(':reply_l:', Config.FluxerTempEmojiGuildId)
    const fluxerEmojiReplyR = await fluxerClient.resolveEmoji(':reply_r:', Config.FluxerTempEmojiGuildId)

    const discordEmojiReplyL = await discordClient.application?.emojis.create({
      attachment: replyL,
      name: 'reply_l'
    })

    const discordEmojiReplyR = await discordClient.application?.emojis.create({
      attachment: replyR,
      name: 'reply_r'
    })

    fs.writeFileSync(Config.DataFolderPath + '/fluxcord.json', JSON.stringify({
      autoGenerated: "This file is automatically generated by Fluxcord. Please do not touch it!",
      fluxerReplyEmoji: {
        replyL: fluxerEmojiReplyL,
        replyR: fluxerEmojiReplyR
      },
      discordReplyEmoji: {
        replyL: discordEmojiReplyL?.id,
        replyR: discordEmojiReplyR?.id
      }
    }))
    log('META', 'First time setup done! Enjoy using the bot!')
  }
})

discordClient.on(DiscordEvents.ClientReady, async () => {
  log('DISCORD', `${discordClient.user?.tag} is ready!`)
})

process.on('uncaughtException', (error) => {
  log('META', 'A uncaught exception occurred.', error)
});

process.on('unhandledRejection', (reason, promise) => {
  log('META', 'A unhandled rejection occurred.', reason)
});

discordClient.login(Config.DiscordBotToken);
fluxerClient.login(Config.FluxerBotToken);