import {
  Events as FluxerEvents,
  Client as FluxerClient,
  EmbedBuilder,
} from "@fluxerjs/core";
import {
  Client as DiscordClient,
  Events as DiscordEvents,
  GatewayIntentBits,
} from "discord.js";
import Config from "./config";
import {
  FluxerCreateMessageHandler,
  FluxerDeleteMessageHandler,
  FluxerUpdateMessageHandler,
} from "./utils/FluxerHandler";
import {
  DiscordCreateMessageHandler,
  DiscordDeleteMessageHandler,
  DiscordUpdateMessageHandler,
} from "./utils/DiscordHandler";
import { log } from "./utils/Logger";
import fs from "node:fs";
import { ChannelMap } from "./db";

const discordClient: DiscordClient<boolean> = new DiscordClient({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

const maps = await ChannelMap.findAll();

const fluxerClient = new FluxerClient({
  intents: 0,
  presence: {
    status: "online",
    custom_status: {
      text: `${Config.BotPrefix}help | bridging ${maps.length} channel${maps.length > 1 ? "s" : ""}`,
    },
  },
});

discordClient.on(DiscordEvents.MessageCreate, async (msg) => {
  if (msg.author.id === discordClient.user?.id) return;
  try {
    await DiscordCreateMessageHandler(msg, discordClient, fluxerClient);
  } catch (e) {
    await msg.reply({
      embeds: [
        // @ts-expect-error
        new EmbedBuilder()
          .setTitle("A error has occurred while bridging this message!")
          .setDescription(
            "Please ping <@1471779547901222947> on https://fluxer.gg/6ULDiF2g showing this error.",
          )
          .addFields({
            name: "Stack trace",
            value: `${e}`,
          }),
      ],
    });
  }
});

discordClient.on(DiscordEvents.MessageUpdate, async (oldMsg, newMsg) => {
  try {
    await DiscordUpdateMessageHandler(oldMsg, newMsg, fluxerClient);
  } catch (e) {
    log("FLUXER", e);
  }
});

discordClient.on(DiscordEvents.MessageDelete, async (msg) => {
  try {
    await DiscordDeleteMessageHandler(msg, fluxerClient);
  } catch (e) {
    log("FLUXER", e);
  }
});

fluxerClient.on(FluxerEvents.MessageCreate, async (msg) => {
  try {
    if (msg.author.id === fluxerClient.user?.id) return;
    await FluxerCreateMessageHandler(msg, fluxerClient, discordClient);
  } catch (e) {
    await msg.reply({
      embeds: [
        new EmbedBuilder()
          .setTitle("A error has occurred while bridging this message!")
          .setDescription(
            "Please ping <@1471779547901222947> on https://fluxer.gg/6ULDiF2g showing this error.",
          )
          .addFields({
            name: "Stack trace",
            value: `${e}`,
          }),
      ],
    });
  }
});
fluxerClient.on(FluxerEvents.MessageUpdate, async (oldMsg, newMsg) => {
  try {
    await FluxerUpdateMessageHandler(oldMsg, newMsg, discordClient);
  } catch (e) {
    log("DISCORD", e);
  }
});
fluxerClient.on(FluxerEvents.MessageDelete, async (msg) => {
  try {
    FluxerDeleteMessageHandler(msg, discordClient);
  } catch (e) {
    log("DISCORD", e);
  }
});

fluxerClient.on(FluxerEvents.Ready, async () => {
  log(
    "FLUXER",
    `${fluxerClient.user?.username}#${fluxerClient.user?.discriminator} is ready!`,
  );

  if (!fs.existsSync(Config.DataFolderPath + "/fluxcord.json")) {
    log("META", "Welcome to Fluxcord! Doing first-time setup...");
    const replyL = fs.readFileSync(Config.DataFolderPath + "/reply-l.webp");
    const replyR = fs.readFileSync(Config.DataFolderPath + "/reply-r.webp");

    const fluxerGuild = await fluxerClient.guilds.fetch(
      Config.FluxerTempEmojiGuildId,
    );
    await fluxerGuild?.createEmojisBulk([
      {
        image: replyL.toBase64(),
        name: "reply_l",
      },
      {
        image: replyR.toBase64(),
        name: "reply_r",
      },
    ]);

    const fluxerEmojiReplyL = await fluxerClient.resolveEmoji(
      ":reply_l:",
      Config.FluxerTempEmojiGuildId,
    );
    const fluxerEmojiReplyR = await fluxerClient.resolveEmoji(
      ":reply_r:",
      Config.FluxerTempEmojiGuildId,
    );

    const discordEmojiReplyL = await discordClient.application?.emojis.create({
      attachment: replyL,
      name: "reply_l",
    });

    const discordEmojiReplyR = await discordClient.application?.emojis.create({
      attachment: replyR,
      name: "reply_r",
    });

    fs.writeFileSync(
      Config.DataFolderPath + "/fluxcord.json",
      JSON.stringify({
        autoGenerated:
          "This file is automatically generated by Fluxcord. Please do not touch it!",
        fluxerReplyEmoji: {
          replyL: fluxerEmojiReplyL,
          replyR: fluxerEmojiReplyR,
        },
        discordReplyEmoji: {
          replyL: discordEmojiReplyL?.id,
          replyR: discordEmojiReplyR?.id,
        },
      }),
    );
    log("META", "First time setup done! Enjoy using the bot!");
  }
});

discordClient.on(DiscordEvents.ClientReady, async () => {
  log("DISCORD", `${discordClient.user?.tag} is ready!`);

  discordClient.user?.setActivity(
    `${Config.BotPrefix}help | bridging ${maps.length}  channel${maps.length > 1 ? "s" : ""}`,
  );
});

process.on("uncaughtException", (error) => {
  log("DEBUG", "A uncaught exception occurred.", error);

  try {
    discordClient.destroy();
  } catch {}

  try {
    fluxerClient.destroy();
  } catch {}

  process.exit(1);
});

process.on("unhandledRejection", (reason, promise) => {
  log("DEBUG", "A unhandled rejection occurred.", reason);

  try {
    discordClient.destroy();
  } catch {}

  try {
    fluxerClient.destroy();
  } catch {}

  process.exit(1);
});

discordClient.login(Config.DiscordBotToken);
fluxerClient.login(Config.FluxerBotToken);
